[package]
name = "diffdiagram"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.3"
url = "2.4"
tree-sitter = "0.20.10"
tree-sitter-loader = "0.20"
regex = "1.8"
petgraph = "0.6.3"
unidiff = "0.3"
serde = "1.0"
serde_json = "1.0"
dirs = "5.0"
